services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mqttData:/mosquitto/data
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=gardenometer_user
      - POSTGRES_DB=gardenometer_db
volumes:
  pgdata:
  mqttData:
